"""
Hint Service — Three-Stage Progressive Hints
============================================

When a child answers incorrectly, the system provides progressive help:

  Stage 0 — **Encourage**: "再想想哦！💪" — a gentle nudge to try again.
  Stage 1 — **Hint**: A structural hint drawn from the question's
            ``hints`` list (e.g. "注意第一段的关键词").
  Stage 2 — **Explain**: The full explanation, either from the question's
            ``explanation`` field or generated by an LLM (optional).

Each stage is only revealed if the child answers wrong again.  This keeps
the challenge alive while ensuring the child is never stuck.
"""

from __future__ import annotations

from typing import Any

from deeptutor.services.gamification.models import Question
from deeptutor.services.gamification.safety import SafetyFilter

# ---------------------------------------------------------------------------
# Stage constants
# ---------------------------------------------------------------------------

STAGES: list[str] = ["encourage", "hint", "explain"]
MAX_STAGE: int = len(STAGES) - 1  # 2


# Default encouragement copy (Chinese primary, English fallback).
_DEFAULT_ENCOURAGE_ZH: list[str] = [
    "再想想哦！💪 我相信你可以的！",
    "差一点点啦！换个角度试试？🌟",
    "没关系，我们再来一次！😊",
]

_DEFAULT_ENCOURAGE_EN: list[str] = [
    "Try again! I believe in you! 💪",
    "Almost there! Think from another angle? 🌟",
    "That's okay, let's try once more! 😊",
]

_DEFAULT_EXPLANATION_ZH: str = "这道题的正确答案已经在阅读材料中提到啦，再仔细看看吧！📖"
_DEFAULT_EXPLANATION_EN: str = (
    "The correct answer is mentioned in your reading material. Take another look! 📖"
)


class HintService:
    """Three-stage progressive hint provider.

    Stage progression:
      0 → encourage (gentle retry prompt)
      1 → hint (structural hint from question data)
      2 → explain (full explanation, optionally LLM-generated)
    """

    def __init__(
        self,
        safety_filter: SafetyFilter | None = None,
        language: str = "zh",
    ) -> None:
        self._safety = safety_filter or SafetyFilter()
        self._language = language
        self._call_count: int = 0

    def get_hint(self, q: Question, stage: int) -> str:
        """Return the hint text for the given stage.

        Args:
            q: The question the child is struggling with.
            stage: Hint stage (0 = encourage, 1 = hint, 2 = explain).

        Returns:
            The hint text, safety-filtered.
        """
        stage = max(0, min(stage, MAX_STAGE))

        if stage == 0:
            return self._encourage()

        if stage == 1:
            return self._structural_hint(q)

        # stage == 2 → explain
        return self._explanation(q)

    async def get_explanation(
        self,
        q: Question,
        llm_client: Any | None = None,
    ) -> str:
        """Generate or retrieve the full explanation (stage 2+).

        When an ``llm_client`` is available, it is asked to generate a
        child-friendly explanation.  The result is safety-filtered before
        being returned.

        Args:
            q: The question to explain.
            llm_client: Optional LLM with ``async complete(prompt)``.

        Returns:
            The explanation text.
        """
        if llm_client is not None:
            try:
                prompt = self._build_explanation_prompt(q)
                raw = await llm_client.complete(prompt)
                filtered = self._safety.check_explanation(raw, "")
                if filtered.passed:
                    return filtered.sanitized_text
            except Exception:
                pass

        # Fall back to stored explanation or default
        return self._explanation(q)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _encourage(self) -> str:
        """Pick an encouragement message using a deterministic rotation."""
        idx = self._call_count % 3
        self._call_count += 1
        if self._language == "zh":
            return _DEFAULT_ENCOURAGE_ZH[idx]
        return _DEFAULT_ENCOURAGE_EN[idx]

    def _structural_hint(self, q: Question) -> str:
        """Return a structural hint from the question's hints list."""
        if q.hints:
            hint_idx = min(0, len(q.hints) - 1)
            hint_text = q.hints[hint_idx]
        else:
            # Generate a generic structural hint
            if self._language == "zh":
                if q.options:
                    hint_text = "提示：仔细看看每个选项，排除掉明显不对的。🔍"
                elif q.question_type == "fill_blank":
                    hint_text = "提示：答案就在文章里，注意关键词哦！🔍"
                elif q.question_type == "true_false":
                    hint_text = "提示：回到原文找找线索吧！🔍"
                else:
                    hint_text = "提示：再仔细读读题目要求。🔍"
            else:
                if q.options:
                    hint_text = "Hint: Look at each option carefully and eliminate wrong ones. 🔍"
                elif q.question_type == "fill_blank":
                    hint_text = "Hint: The answer is in the text. Look for keywords! 🔍"
                elif q.question_type == "true_false":
                    hint_text = "Hint: Go back to the passage for clues! 🔍"
                else:
                    hint_text = "Hint: Read the question requirements carefully. 🔍"

        return hint_text

    def _explanation(self, q: Question) -> str:
        """Return the explanation from the question or a default."""
        if q.explanation:
            return q.explanation
        if self._language == "zh":
            return _DEFAULT_EXPLANATION_ZH
        return _DEFAULT_EXPLANATION_EN

    def _build_explanation_prompt(self, q: Question) -> str:
        """Build an LLM prompt for generating a child-friendly explanation."""
        options_text = ""
        if q.options:
            options_text = f" Options: {', '.join(q.options)}."
        return (
            f"You are a friendly tutor explaining an answer to a child.\n"
            f"Question: {q.text}{options_text}\n"
            f"Correct Answer: {q.correct_answer}\n"
            f"Explain why this is correct in a simple, encouraging way. "
            f"Use at most 2 sentences."
        )


__all__ = [
    "HintService",
    "STAGES",
    "MAX_STAGE",
]
